### ISSUE TITLE
Fetching customers with specific username gets all the customers

### ISSUE THREAD

**Issue by dev-ahmedmahmoud** [woocommerce/wc-api-dev#103]
Steps to reproduce the issue:

1. conduct a get request to fetch customers
2. add username="value" as a query parameter
3. log the the returned customers

Expected/actual behavior:

When I follow those steps, I see the list of the whole customers returned

I was expecting to see only the list of the customers whose usernames match the passed query value

**Comment by mikejolley** [comment]
Username is not documented.

https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-customers
