### ISSUE TITLE
Products - date created is read only via the API, but updatable within admin

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/wc-api-dev#104]
`date_created` is a read only field but I'm not sure why. Can/should this be made editable in the next version?

Request was here https://github.com/woocommerce/woocommerce/issues/19731

cc @claudiosanches

**Comment by callumstrubi** [comment]
This is achievable trivially with the hook:

```php
add_filter("woocommerce_rest_pre_insert_product_object", function($product, $request, $creating){
	if($request['date'] || $request['date_gmt']){
		$date = new \DateTime(($request['date_gmt'] ? $request['date_gmt'] : $request['date']), new \DateTimeZone('UTC'));
		$product->set_date_created($date->format('U'));
	}
	return $product;
}, 10, 3);

**Comment by claudiosanches** [comment]
Solved in https://github.com/woocommerce/woocommerce/issues/21117

**Comment by callumstrubi** [comment]
Ah excellent, didn't see this in the release notes for 3.5 - do we expect this to be compatible with my hook, or do i need to do testing?

**Comment by claudiosanches** [comment]
@callumstrubi we should write a blog post about REST API v3 in the next weeks. About your hook should still work, but probably you should stop using it in v3.

**Comment by callumstrubi** [comment]
API v3 will come with a new endpoint though right? So we can plan migration effectively - thank you for the update and hard work in a v3 (WP limitations are constraining v2 too much).

**Comment by claudiosanches** [comment]
Comes inside `wc/v3` instead of `wc/v2`, so yes, you can do a migration to all new endpoints, test before and so on.

**Comment by callumstrubi** [comment]
Sorry for comment spam - will wc-api-php be upgraded to support the v3 endpoint in line with it's release or will that come in the following months?

**Comment by claudiosanches** [comment]
@callumstrubi already supports, just set the library to connect to v3.

Example:

```php
require __DIR__ . '/vendor/autoload.php';

use Automattic\WooCommerce\Client;

$woocommerce = new Client(
    'http://example.com', 
    'ck_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 
    'cs_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    [
        'wp_api' => true,
        'version' => 'wc/v3',
    ]
);
```
