### ISSUE TITLE
Media Endpoint [ Idea / Suggestion ]

### ISSUE THREAD

**Issue by steffanhalv** [woocommerce/wc-api-dev#105]
Woo supports adding downloadable files for products, but right now there is no way to upload this files using woo rest api.

Same issue for images / gallery / featured image.
(You can clone an image from an url though, but not upload from Desktop)

Surely you can use wp-json/wp/v2/media, but that needs additional permission -
**Ref:** https://github.com/woocommerce/woocommerce/issues/19730#issuecomment-381902004

What about adding a clone of this endpoint to Woo, or just open up for this specific endpoint through Woo oauth as an exception from the other WP Endpoints ?

**Comment by claudiosanches** [comment]
See my comment on https://github.com/woocommerce/woocommerce/issues/19730#issuecomment-382059050

Better install an authentication plugin and fetch from both, instead of creating a clone of that endpoint just to use WooCommerce authentication method.

**Comment by claudiosanches** [comment]
Here a few authentication options for WordPress: https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/#authentication-plugins
