### ISSUE TITLE
Filtering products using attributes does not work

### ISSUE THREAD

**Issue by dev-ahmedmahmoud** [woocommerce/wc-api-dev#107]
I have an attribute called "Flavor" with ID: 1 and an attribute_term within the flavor attribute called "Banana" with ID:23 ... when I try to retrieve products with Banana Flavor using the following query:

`this.WooCommerce.getAsync(`products/?attribute=1&attribute_term=23&page=1`).then( async (data) => {
      let newProducts = JSON.parse(data.body);
      console.log(newProducts)
    }, (err) => {
      console.log(err)
    });` 

I get the entire list of existing products.

**Comment by mikejolley** [comment]
Duplicate https://github.com/woocommerce/woocommerce/issues/19915
