### ISSUE TITLE
Support for multiple order statuses when filtering a get request

### ISSUE THREAD

**Issue by callumstrubi** [woocommerce/wc-api-dev#108]
Previous versions of the API supported this, and it is a fairly simple yet hugely beneficial feature to be able to filter by multiple statuses with a single request. These could be comma delimited as with the previous version.

**Comment by KristapsBerzins** [comment]
Same could be applied to type and status properties for any other requests. e.g. products

**Comment by claudiosanches** [comment]
This is already done in REST API v3.
