### ISSUE TITLE
Add a field indicating a note "type" to the order notes api

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/wc-api-dev#109]
We'd like to create a view in the mobile app that visually distinguishes between different types of notes:
- System status
- Note to customer
- Private note

The API currently only provides `customer_note=true|false` which is fine for determining a public vs private note, but no data is provided that would allow us to flag a note as "system generated". Wp-admin uses different colors to represent the system generated status so it looks like something we do track:

![screen shot 2018-04-30 at 4 24 21 pm](https://user-images.githubusercontent.com/5810477/39453498-625f7202-4c93-11e8-8f72-7f06172dc8d1.png)

**Comment by aforcier** [comment]
It looks like this is [already supported in the V3 API](https://github.com/woocommerce/wc-api-dev/blob/27a57b3f8c710ff68d2121c2b2e159eaec8f9e94/api/class-wc-rest-dev-order-notes-controller.php#L41), so I assume we'd be able to use it once V3 is rolled out to core.

The notes returned from the API will have an `author` field, which is either `"system"` or a username on the site.

**Comment by claudiosanches** [comment]
Closing since it's already part of v3.
