### ISSUE TITLE
After/before date filtering does not fully support ISO 8601 

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/wc-api-dev#110]
This is a known WP core issue: https://core.trac.wordpress.org/ticket/41032 which was logged here:

https://github.com/woocommerce/woocommerce/issues/19976

> As the support for the ISO 8601 spec of date format is not quite correct, you cannot specify the timezone that the date is transmitted in. As such I propose that all dates are assumed to be UTC and are handled as such even when the default timezone is not running in UTC. Alternatively, proper implementation of the ISO 8601 spec would allow for the timezone to be sent along with the DateTime of such filters.

It might be possible to work around this and handle after/before timezone conversion our side. Needs investigation.

**Comment by claudiosanches** [comment]
We should help WordPress core fix it first.

**Comment by claudiosanches** [comment]
Closing, since it's not an issue on our side, we could help patch it on WordPress.
