### ISSUE TITLE
Support for hourly stats granularity

### ISSUE THREAD

**Issue by aforcier** [woocommerce/wc-api-dev#111]
With some new stats endpoints being worked on, perhaps an hour-by-hour sales/revenue/etc breakdown by day could be one of the options added to the API?

(This has come up in the context of the mobile apps.)

**Comment by claudiosanches** [comment]
We are starting work on a new reports endpoint that should work hour-by-hour, closing since this is already an working in progress.

**Comment by folletto** [comment]
Can you add a link to the issue/PR tracking this change? Thanks :)

**Comment by claudiosanches** [comment]
@folletto no issues or PR for now.
