### ISSUE TITLE
shipping_lines response - include `instance id` field

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/wc-api-dev#113]
Reported here https://github.com/woocommerce/woocommerce/issues/20373

3.4 split and formalised method id/instance ids which were previously colon separated.

We should introduce a separate `instance_id` field so rates can be distinguished if they are from the same shipping method.

**Comment by thehill383** [comment]
@mikejolley i am really pleased that you understood my issue, first time for getting involved on github. i am equally as pleased that you agree that it should be added.

**Comment by claudiosanches** [comment]
Solved in https://github.com/woocommerce/woocommerce/issues/21116
