### ISSUE TITLE
Ability to fetch a list of orders matching more than one status, bonus using a status search wildcard

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/wc-api-dev#114]
Currently the Woo API endpoint for /orders only allows filtering by a single order status. It would be helpful if we could pass in a list or array of order statuses to match results on. Example:
```
"status":"processing, pending, on-hold"
```
or
```
"status":{"processing", "pending", "on-hold"}
```

An even cooler feature would be to allow for wildcard matching on an order status filter:
```
"status":"wc-%"
```
in this example above the `%` would be the wildcard and an example of statuses it would match would be:
- wc-new-order
- wc-yay
- wc-red

Thanks!

**Comment by claudiosanches** [comment]
REST API v3 already supports multiple statuses, but we are not looking for a wildcard, maybe we can look at it in the future, please feel free to submit a Pull Request if you should like to implement it, you can submit to WooCommerce core. Thanks.
