### ISSUE TITLE
Add total order count in the metadata of the /orders endpoint

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/wc-api-dev#116]
**Use Case**
Need a way to get a total count of orders for a site that allows for providing an optional filter (or ideally a range of filters as requested in #114). 

**Possible Implementation**
This could be a standalone endpoint but it may make it more flexible if it were included in the metadata of the `GET /orders` response. So if we send in a request for orders, regardless of per_page value, the metadata would include an element containing the total orders available for the order status filter provided (or ANY if none provided). Having an additional element that lists total orders regardless of filter may also be nice.

**Comment by claudiosanches** [comment]
This already is listed in the headers, also when filtering by statuses (and our REST API v3 accepts multiple statuses now), and we included a new endpoint to list total of orders for each status in `GET /wp-json/wc/v3/reports/orders/totals`.
