### ISSUE TITLE
Is there a target date for v4?

### ISSUE THREAD

**Issue by benignant** [woocommerce/wc-api-dev#127]
WooCommerce 3.6 doesn't seem to be coming with v4.

> This will comes with WooCommerce 3.6.
> 
> _Originally posted by @claudiosanches in https://github.com/woocommerce/wc-api-dev/issues/65#issuecomment-454885904_

**Comment by claudiosanches** [comment]
Will come when we merge WooCommerce Admin into core, or maybe early, but we don't have a specific timeline for it yet, since depend on more projects.
