### ISSUE TITLE
Retrieve orders by date modified in 3.6

### ISSUE THREAD

**Issue by MioPedersen** [woocommerce/wc-api-dev#128]
In this #65 thread it is mentioned that filtering by date_modified in the REST API would be available in WooCommerce 3.6, but after reading the change log I could not seem to find it mentioned? 

Will WooCommerce 3.6 support this feature? We have been waiting for it for a long time, and it is pretty critical for our integration.

I opened a new issue because commenting was limited to collaborators on the other thread.

**Comment by mikejolley** [comment]
No this was not done, and the milestone is set for the v4 api. I will reopen comms on the other issue and clean out the spam comments.

If you'd like to contribute to ensure this does get in, by all means please do. Core WC does not currently have a need for this feature.

**Comment by MioPedersen** [comment]
@mikejolley I'm pretty disappointed that this change on such short notice. We have been waiting this feature a long time.

Is there any ETA for v4?

**Comment by mikejolley** [comment]
@MioPedersen short notice?

No there is not an ETA. You're welcome to contribute to this if you'd like to make sure it makes it gets in.
