### ISSUE TITLE
API - woocommerce_currency should return separate field for symbol

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/wc-api-dev#2]
```
When using the wc-api to get general settings /wc/v2/settings/general, the woocommerce_currency object has an options array that has the following format:

{AED: "United Arab Emirates dirham (&#x62f;.&#x625;)"}

This results in having to use a regex to separate the country and currency name from the currency symbol.

I propose that the options object should take this format:

{ AED: { country: "United Arab Emirates", currency: "dirham", symbol: "&#x62f;.&#x625;" } }
```

It may be good to look into a data endpoint instead/in addition, since this is a setting, not a way to get the correct symbol.

From https://github.com/woocommerce/woocommerce/issues/15101

**Comment by belcherj** [comment]
When showing a dropdown in settings a user may not want to show the full country plus the symbol.  Calling a second endpoint to get just the symbols seems needless.  Breaking out the data into fields makes the API more flexible.
