### ISSUE TITLE
Orders: Get "new" orders from one API request

### ISSUE THREAD

**Issue by ryelle** [woocommerce/wc-api-dev#26]
For store on calypso, "new" orders are any in 'pending', 'processing', or 'on-hold'. If I want to get those orders via the API, I can't do it in one request - currently `status` only accepts a single status string, or 'any', but no (apparent) way to request a subset of statuses.

One solution would be to pass in a list of statuses, `status[]=pending&status[]=processing&status[]=on-hold`, and returning all orders that match one of those. This would be useful for other combined status listings, like if we wanted to include completed, cancelled (and refunded?) orders in a list of "finished" orders.

Another solution would be to allow the API to accept `status=new`, and behind the scenes translate that to `[ pending, processing, on-hold ]`. If wc extensions can add custom statuses, this might be better so they can indicate if some new status should be considered "new".

**Comment by ryelle** [comment]
CC'ing @justinshreve & @mikejolley so we can talk about an approach here before I do anything 🙂

**Comment by mikejolley** [comment]
Using `new` could be dangerous if someone had a custom status, or we wanted to use that status name in the future. I prefer the array idea, or a comma separated list of statuses.

@claudiosanches

**Comment by claudiosanches** [comment]
> One solution would be to pass in a list of statuses, status[]=pending&status[]=processing&status[]=on-hold, and returning all orders that match one of those. This would be useful for other combined status listings, like if we wanted to include completed, cancelled (and refunded?) orders in a list of "finished" orders.

You can just use like other fields and accept a list, like:

```
status=pending,processing,on-hold
```
