### ISSUE TITLE
Excluding subscriptions from /orders

### ISSUE THREAD

**Issue by alexbouchardd** [woocommerce/wc-api-dev#29]
Hey there!

I need to make a GET at /orders that only return unique orders (that are not subscriptions). That filter is currently showing in the WooCommerce dashboard:

![screen_shot_2017-07-18_at_3_30_04_pm](https://user-images.githubusercontent.com/2049224/28335988-4c8d12a0-6bce-11e7-97f8-6011b27e574a.png)

However, I can't seem to find a way to do it via the REST API, is that currently doable? The only solution I can think of right now is to remove the subscriptions client-side but because of the paging that is extremely inconvenient. 

Cheers

**Comment by mikejolley** [comment]
This I don't believe is possible and would require subscriptions to extend the functionality of the API.
