### ISSUE TITLE
General Api missing a lot of features.

### ISSUE THREAD

**Issue by ghost** [woocommerce/wc-api-dev#50]
Can we have some api to calculate tax, filter shipping method based on country, state, zip code inputs. I am trying to use the api to make same features as woocommerce checkout page. The countries and states for billing and shipping should be dynamic based on the general settings in the woocommerce setting.

**Comment by ghost** [comment]
I am trying to get shipping methods and taxes based on country, state, zip code, city and product in the cart page using rest api. Also get the billing countries and states based on the woocommerce settings through rest api. These features will definitely make woocommerce rest api the best. Please create rest api to make the functions happen. PLEASE.

**Comment by ghost** [comment]
no luck?

**Comment by ajayghaghretiya** [comment]
@selotoprak You can make the custom endpoint to get the available shipping countries and also get the available selling countries through rest api.

**Comment by ajayghaghretiya** [comment]
You can use like this.

$countries_obj     = new WC_Countries();
	$countries_details = array();

	$countries = $countries_obj->get_shipping_countries();
	if ( ! empty( $countries ) ) {
		foreach ( $countries as $code => $country ):
			$countries_details['country_code'] = $code;
			$countries_details['country_name'] = $country;
			if ( ! empty( $code ) ) {
				$states_details_arr = array();
				$states             = $countries_obj->get_states( $code );
				foreach ( $states as $code => $state ):
					$states_details['state_code'] = $code;
					$states_details['state_name'] = $state;
					$states_details_arr[]         = $states_details;
				endforeach;
				$countries_details['states'] = $states_details_arr;
			}
			$country_details_arr[] = $countries_details;
		endforeach;
		$response['countries'] = $country_details_arr;
	}
	$response['code'] = 200;

	return $response;

**Comment by ghost** [comment]
Thank you.  I will look in to it.

**Comment by mikejolley** [comment]
This is best for a custom API for now. Our API does not cover frontend activities, only data.
