### ISSUE TITLE
Change Order lines product prices and shippingcost 

### ISSUE THREAD

**Issue by sbosman1** [woocommerce/wc-api-dev#52]
Hello,

alot of our customers want us to change the order line product price and the shippingcost of the order. At the moment nothing can be changed. Will this be possible soon?

**Comment by peterfabian** [comment]
Hi, 

maybe I misunderstood, but sending a PUT request to the `wp-json/wc/v2/orders/#order_id` seems to change the price of product and shipping cost for the order?

e.g. 

```
curl -X PUT \
  https://local.wordpress.test/wp-json/wc/v2/orders/#order_id \
  -H 'authorization: ... \
  -H 'content-type: application/json' \
  -d '{
    "line_items": [
        {
            "id": 29,
            "product_id": 11,
            "subtotal": "47.00",
            "subtotal_tax": "0.00",
            "total": "47.00",
            "total_tax": "0.00",
            "sku": "woo-hoodie-with-logo",
            "price": 47
        }
    ],
    "tax_lines": [],
    "shipping_lines": [
        {
            "id": 30,
            "method_title": "Flat rate",
            "method_id": "flat_rate",
            "instance_id": "1",
            "total": "12.00",
            "total_tax": "0.00",
            "taxes": []
        }
    ]
}'
```

**Comment by claudiosanches** [comment]
As Peter said, it's already possible to change the prices. Probably you are using a legacy version of WooCommerce REST API.
You can check the doc for the latest version in https://woocommerce.github.io/woocommerce-rest-api-docs/
