### ISSUE TITLE
Missing `enabled` value for variations

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/wc-api-dev#64]
This is based on post status and is missing from the API. Core allows variations to be enabled and disabled.

@claudiosanches 

Ref: https://github.com/woocommerce/woocommerce/issues/17249

**Comment by claudiosanches** [comment]
In fact is possible using `visible`, but currently have a wrong description.

**Comment by scottbasgaard** [comment]
Thanks guys, should get this one updated in docs:

>Define if the attribute is visible on the “Additional information” tab in the product’s page. Default is true.

**Comment by jamesckemp** [comment]
The `visible` parameter of a variation seems to always return `true` if the parent is visible, and `false` if it isn't. It ignores the `enabled` setting, from what I can see.

Updating the `visible` setting via the API works to trigger the `enabled` checkbox, but it still comes back based on the parent's visibility.

**Comment by claudiosanches** [comment]
We introduced `status`, so it's possible now to fully control if an variation is enabled: https://github.com/woocommerce/wc-api-dev/pull/4

**Comment by ThomasVeld** [comment]
Could this be fixed in V2? Enabled is always returning true, and not every user is on WC 3.6 yet.
