### ISSUE TITLE
Woocommrece Rest Api V2 Sorting Product with default WordPress Options and Getting Country and State list

### ISSUE THREAD

**Issue by IntelliJAbhishek** [woocommerce/wc-api-dev#69]
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [X] I have included a failing test as a pull request (Optional)

I'm using woocommerce RestApi v2 in Android. There is sorting options: `date`, `id`, `include`, `title` and `slug`. Default is `date`.

1) I want to know that how to do sorting by  `Default Sorting` ,`Sort By Popularity`,`Sort By Average Rating`,`Sort by newness`,`Sort by Price: low to high`,`Sort By Price:high to low` . These option is by default availabe at shop page but how to do in api?

2) How to get country [ Name,Code] and its states?
I got in php we can do this-

       global $woocommerce;
       $countries_obj   = new WC_Countries();
       $countries   = $countries_obj->__get('countries');
       $default_country = $countries_obj->get_base_country();
       $default_county_states = $countries_obj->get_states( $default_country );`

how can I do this via rest api? without using php api?

**Comment by ajayghaghretiya** [comment]
You can create API endpoint For WooCommerce countries. where you can make your custom code for getting the countries from the WooCommerce send the response to the API.
