### ISSUE TITLE
Support querying orders by multiple statuses

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/wc-api-dev#73]
https://github.com/woocommerce/woocommerce/pull/17598#discussion_r151813748

> In order to change to allowing multiple statuses, the args for the endpoint would need to be changed to type => array. I didn't make this change because I didn't want to potentially break or change existing API functionality.

**Comment by ryelle** [comment]
This is already done, since we needed it for order filtering in Calypso 🙂  See https://github.com/woocommerce/wc-api-dev/pull/31 — is there another improvement to this you were looking for?

**Comment by mikejolley** [comment]
I didn't see it :) Thanks 👍
