### ISSUE TITLE
Ability to set 'onbackorder' stock status for products

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/wc-api-dev#75]
Related to https://github.com/woocommerce/woocommerce/issues/11259

WC 3.3 introduces a new 'onbackorder' stock status for products. 

For products that have stock management enabled the status automatically gets changed to 'onbackorder' when inventory is below 0 and backorders are allowed, so we don't have to do anything special for that situation.

For products that don't have stock management enabled, there is no way to set the 'onbackorder' status through the API.

Here are two relevant product properties from the API:

`in_stock | boolean | Controls whether or not the product is listed as “in stock” or “out of stock” on the frontend. Default is true.` (No way to make this toggle between 'instock', 'outofstock', and 'onbackorder' statuses)

`backordered | boolean | Shows if the product is on backordered.READ-ONLY` (This is read only)

I think we have a few potential options here:
1. Make the `backordered` property not read only and set 'onbackorder' status if it is true.
2. Deprecate `in_stock` in favor of a new param called `stock_status`. This will let us use any current or future stock statuses.
3. Make valid params for `in_stock` be `true`, `false`, and `onbackorder`.

These changes would be for API v3.

**Comment by claudiosanches** [comment]
> Make valid params for in_stock be true, false, and onbackorder

We just need to make sure to not create mixed fields, so probably better use this field as string, or even change to `stock_status` and then return all as strings like `in_stock`, `not_in_stock` and `backordered`.

**Comment by claudiosanches** [comment]
Already solved in #21316
