### ISSUE TITLE
Gutenberg conflict

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/wc-api-dev#77]
This plugin is currently breaking Gutenberg.

https://cloudup.com/cpJVAVO5GuL

Seems to be related to this:

https://github.com/woocommerce/wc-api-dev/blob/6c7e95e/api/class-wc-rest-dev-data-currencies-controller.php#L57

**Comment by aduth** [comment]
>Seems to be related to this:
>
>https://github.com/woocommerce/wc-api-dev/blob/6c7e95e/api/class-wc-rest-dev-data-currencies-controller.php#L57

Specifically, the pattern looks to be invalid, where I'd expect `[\w-]{3}+` to be one of either `[\w-]{3,}` or `[\w-]{3}`.
