### ISSUE TITLE
Adding and removing coupons from orders, with calculation

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/wc-api-dev#78]
Related to https://github.com/woocommerce/woocommerce/pull/18236

The current API supports the old way of updating coupons - manually. You handle both the update of line item prices, and the setting of the discount total.

Ref https://woocommerce.github.io/woocommerce-rest-api-docs/#order-properties where discount_total is defined in the API call.

For the next version of the API it would be great to add a new method or endpoint to apply a coupon (or remove a coupon) from an order and have everything done for you, in the same way you can now apply/remove coupons in WP admin by entering the coupon code.

cc @claudiulodro @claudiosanches for endpoint feedback. What would be the optimal solution?

**Comment by ryelle** [comment]
So the suggestion is a new endpoint under orders/:id, allowing the CRUD behavior for coupons? Like this?

```
GET /orders/<id>/coupons -- get list of currently applied coupons, also returned in order response
POST /orders/<id>/coupons -- add a coupon/list of coupons to an order
```

The `POST` endpoint could take a list of objects, with a set code to add a coupon, and `{ id: ID, code: null }` to delete the coupon, like what's done for order items. This would work great for the calypso use case 🙂

**Comment by mikejolley** [comment]
That sounds good to me @ryelle. @claudiosanches is this what you had in mind also?

**Comment by razorsharpshady** [comment]
before creating an order there should be an api that gives the total amount after adding items & applying discount. the parameters for that api can be same as create order api. 
endpoint can be order/caculate

**Comment by claudiosanches** [comment]
@mikejolley @ryelle we should make calculations already in the current endpoint, so applying a new discount should give the full discount and not allow to change the total amount, at least on wp-admin we don't allow to modify the coupon amount or even the total discounted in the order.

**Comment by samarthagarwal** [comment]
@mikejolley I tried to add the `discount_total` field to my JSON that contains the order data, but when the final order is placed, the `discount_total` field is ignored. The `order` object that I get after the order is placed has the `discount_total` value equal to 0. Are you sure that we can set it?

**Comment by Zoha131** [comment]
Is this issue resolved? I am facing the same problem using rest api. When I add coupons in "coupon_lines", it does not update discount and total.

**Comment by Hamidaraghi** [comment]
@samarthagarwal discount_total  is read only:
http://woocommerce.github.io/woocommerce-rest-api-docs/#order-properties

**Comment by claudiosanches** [comment]
Solved in https://github.com/woocommerce/woocommerce/issues/21119
