### ISSUE TITLE
Refunds; add ability to refund line items

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/wc-api-dev#83]
Reported in https://github.com/woocommerce/woocommerce/issues/18573

Most of the line item props are read only in API v2, and it's actually not possible to refund line items because there is no way to map them to line items in the parent order.

Core does record the link between order line items and refund line items, in meta, so this could be exposed.

- Most of the props are readonly - https://woocommerce.github.io/woocommerce-rest-api-docs/#order-refund-properties This should be revised. Product ID and so on should probably be read only so they always match the parent order.
- It's completely broken in v2 because some of the props do not match what core expects e.g. qty vs quantity.
- We need to return and allow the user to define _refunded_item_id to link refunded line to order line. This needs to be validated to ensure the line exists in the order.

cc @claudiosanches

**Comment by claudiosanches** [comment]
Already solved in this repository.
Solved in https://github.com/woocommerce/wc-api-dev/pull/84
