### ISSUE TITLE
Add currencyCode and presentation details to data/continents response

### ISSUE THREAD

**Issue by allendav** [woocommerce/wc-api-dev#88]
For each country, add

`currency_code` e.g. `USD`
`currency_pos` e.g. `left`
`thousand_sep` e.g. `,`
`decimal_sep` e.g. `.`
`num_decimals` e.g. `2`

I am thinking that since we are not removing/changing the behavior of the endpoint, but just adding things, that we don't need to do any changes re version

fyi @timmyc @justinshreve

**Comment by timmyc** [comment]
I agree, no need to rev the endpoint for these additions.
