### ISSUE TITLE
How to contribute in WC API?

### ISSUE THREAD

**Issue by ajayghaghretiya** [woocommerce/wc-api-dev#91]
Hello,
I have known about the WooCommerce API. I want to contribute in it.
I have cloned this code in wp-content/plugins.
I have checked the get products API via postman.
If I am changing in this plugin code that not affect in API.
So how can I check it with postman?

**Comment by claudiosanches** [comment]
Need to fork this project, install into your WooCommerce installation in your machine, and make change into the files.
But right now we are moving the code to WooCommerce core, fixing things and making changes, so you can fork the new branch there: https://github.com/woocommerce/woocommerce/pull/20111
